### PR TITLE
convert tallyboard_deltas to svg charts

### PR DESCRIPTION
**Pull request by chrismiceli**
Convert another bar chart used in member info and team info.
https://www.pgdp.org/~chrismiceli/c.branch/tallyboard_deltas/stats/teams/tdetail.php?tid=1&tally_name=P1
https://www.pgdp.org/~chrismiceli/c.branch/tallyboard_deltas/stats/members/mdetail.php?id=393&tally_name=P1

### CODE REVIEW

**Comment by srjfoo** [comment]
I'm getting

`Notice: Undefined variable: error in /home/chrismiceli/public_html/c.branch/tallyboard_deltas/pinc/graph_data.inc on line 144`

`Notice: Undefined variable: error in /home/chrismiceli/public_html/c.branch/tallyboard_deltas/pinc/graph_data.inc on line 149`

In both.

**Comment by chrismiceli** [comment]
> 
> 
> I'm getting
> 
> `Notice: Undefined variable: error in /home/chrismiceli/public_html/c.branch/tallyboard_deltas/pinc/graph_data.inc on line 144`
> 
> `Notice: Undefined variable: error in /home/chrismiceli/public_html/c.branch/tallyboard_deltas/pinc/graph_data.inc on line 149`
> 
> In both.

Whoops. Pushed a fix.

**Comment by srjfoo** [comment]
The main thing that I noticed that we still haven't come to terms with is when the time interval for the data is long enough that the bars just don't show very well. Unlike jpgraph, there doesn't seem to be a minimum width for the bars?

Compare, for instance, [this lifetime graph](https://www.pgdp.org/~chrismiceli/c.branch/tallyboard_deltas/stats/members/mdetail.php?id=949&tally_name=P2&range=all) with [this one](https://www.pgdp.org/~chrismiceli/c.branch/tallyboard_deltas/stats/members/mdetail.php?id=537&tally_name=P2&range=all) (note that I'm viewing it in Charcoal, but it's not much if any better (it's subjective) in the other themes. (And the longer the account has been active in that round, the dimmer the bars get. The 3-ish year one still looks pretty good, but much more than that probably wouldn't.

I'm not sure how much of a difference it makes -- if someone is proofing regularly, the bars will be close enough together to give some solidity at the bottom of the graph. It's unfortunately not something that we can test very well on the test site without generating some fake data.

All that being said, the graphs look good to me. We already knew about the problem with the narrow bars. I'm just still wondering how we should deal with it.

**Comment by chrismiceli** [comment]
> 
> 
> The main thing that I noticed that we still haven't come to terms with is when the time interval for the data is long enough that the bars just don't show very well. Unlike jpgraph, there doesn't seem to be a minimum width for the bars?
> 
> Compare, for instance, [this lifetime graph](https://www.pgdp.org/~chrismiceli/c.branch/tallyboard_deltas/stats/members/mdetail.php?id=949&tally_name=P2&range=all) with [this one](https://www.pgdp.org/~chrismiceli/c.branch/tallyboard_deltas/stats/members/mdetail.php?id=537&tally_name=P2&range=all) (note that I'm viewing it in Charcoal, but it's not much if any better (it's subjective) in the other themes. (And the longer the account has been active in that round, the dimmer the bars get. The 3-ish year one still looks pretty good, but much more than that probably wouldn't.
> 
> I'm not sure how much of a difference it makes -- if someone is proofing regularly, the bars will be close enough together to give some solidity at the bottom of the graph. It's unfortunately not something that we can test very well on the test site without generating some fake data.
> 
> All that being said, the graphs look good to me. We already knew about the problem with the narrow bars. I'm just still wondering how we should deal with it.

I think I can apply a min width to the bars, but I'd prefer to do that in its own MR if possible just to scope this one. I think we're making great progress with this graph effort!

**Comment by srjfoo** [comment]
> I think I can apply a min width to the bars, but I'd prefer to do that in its own MR if possible just to scope this one. I think we're making great progress with this graph effort!

Sounds like a good plan.

**Review by cpeel — APPROVED** [review]

**Review by srjfoo — APPROVED** [review]

**Pull request merged**
