### PR TITLE
1488: Clickable words in Good Words Candidate List

### PR DESCRIPTION
**Pull request by chrismiceli**
surround input with label to ease clicking

 https://www.pgdp.org/~chrismiceli/c.branch/issue_1488

### CODE REVIEW

**Comment by chrismiceli** [comment]
The clickable zone now includes the words
image

**Review by srjfoo — APPROVED** [review]

**Review by 70ray — APPROVED** [review]

**Comment by cpeel** [comment]
If we want to announce this change (I'm on the fence) please include an announcement in this MR.

**Comment by srjfoo** [comment]
> If we want to announce this change (I'm on the fence) please include an announcement in this MR.

I wouldn't give it its own announcement, I don't think. It was an old task, and a small change. If we have a collection of small stuff we might add it? (I'm willing to be overruled if anyone has strong feelings about it.

**Comment by chrismiceli** [comment]
> 
> 
> > If we want to announce this change (I'm on the fence) please include an announcement in this MR.
> 
> I wouldn't give it its own announcement, I don't think. It was an old task, and a small change. If we have a collection of small stuff we might add it? (I'm willing to be overruled if anyone has strong feelings about it.

Works for me.

**Pull request merged**
