### PR TITLE
Add an include_once dependency graphing tool for dev purposes.

### PR DESCRIPTION
**Pull request by bpfoley**
Example use:
```
./SETUP/showdeps.py --mode=graph pinc/base.inc
```
and feed the output into a tool such as https://dreampuf.github.io/GraphvizOnline

### CODE REVIEW

**Review by chrismiceli — COMMENTED** [review]
I think this is the first python script in this repo, right? Would it be an easier script to maintain in another language like a shell script or PHP that we already use copiously?

**Comment by bpfoley** [comment]
Well, #1130 is now a Python script too -- I rewrote it after it went way past my 'shell script complexity threshold'. I'd definitely prefer to keep #1130 as a Python script because there are a few details relating to output buffering and HTTP request and cookie handling that you need to get right for the smoke tests to work reliably. I've figured out how to do them with Python's `subprocess` and `urllib` and I don't really trust PHP not to 'helpfully' do the wrong thing behind our backs.

I'd strongly prefer not to do this tool as a shell script for a few reasons
- the most immediate one is my gut instinct that cumulatively it's above the complexity limit of what I like to do in a shell script: recursion, hash tables, string processing, regexps. All possible, yes, but easy to make mistakes.
-  the string processing and regexp handling would get messier.
-  it relies on a dict to represent the dependencies and bash only got hash tables in v4.0, and macOS is never going to move past v3.2 because that's the last version under GPLv2.

I could rewrite it as PHP, although I think it would be a bit longer and a bit uglier.

Note also that this is just a tool for developer curiosity/convenience. It's not used in CI, installation, or production, so to a certain extent it doesn't really matter if it breaks and nobody can maintain it.

**Comment by cpeel** [comment]
The question is totally valid. I'm ok with python code like this in ancillary places (like CI or dev tools, like here). I wouldn't want to introduce it as a runtime dependency though.

**Review by cpeel — APPROVED** [review]
I thought about seeing if we should move this into a `SETUP/tools/` dir but that whole directory is a hot mess of stuff anyway.

**Comment by chrismiceli** [comment]
> Well, #1130 is now a Python script too -- I rewrote it after it went way past my 'shell script complexity threshold'. I'd definitely prefer to keep #1130 as a Python script because there are a few details relating to output buffering and HTTP request and cookie handling that you need to get right for the smoke tests to work reliably. I've figured out how to do them with Python's `subprocess` and `urllib` and I don't really trust PHP not to 'helpfully' do the wrong thing behind our backs.
> 
> I'd strongly prefer not to do this tool as a shell script for a few reasons
> 
>     * the most immediate one is my gut instinct that cumulatively it's above the complexity limit of what I like to do in a shell script: recursion, hash tables, string processing, regexps. All possible, yes, but easy to make mistakes.
> 
>     * the string processing and regexp handling would get messier.
> 
>     * it relies on a dict to represent the dependencies and bash only got hash tables in v4.0, and macOS is never going to move past v3.2 because that's the last version under GPLv2.
> 
> 
> I could rewrite it as PHP, although I think it would be a bit longer and a bit uglier.
> 
> Note also that this is just a tool for developer curiosity/convenience. It's not used in CI, installation, or production, so to a certain extent it doesn't really matter if it breaks and nobody can maintain it.

This all makes sense, just wanted to make sure we make a conscious choice here and don't just fall back to what is comfortable. In the case we stick with python, I'd vote to have some documentation on Python usage in the repo or at least in the comments of this file that could include
1. Versions of python supported
2. How to invoke the script
3. Which OSes are expected to work (if not all of them)
Does it make sense to add any python linting tools to our CI for these scripts, or is that not a priority for these scripts?

**Comment by bpfoley** [comment]
> > Well, #1130 is now a Python script too -- I rewrote it after it went way past my 'shell script complexity threshold'. I'd definitely prefer to keep #1130 as a Python script because there are a few details relating to output buffering and HTTP request and cookie handling that you need to get right for the smoke tests to work reliably. I've figured out how to do them with Python's `subprocess` and `urllib` and I don't really trust PHP not to 'helpfully' do the wrong thing behind our backs.
> > I'd strongly prefer not to do this tool as a shell script for a few reasons
> > ```
> > * the most immediate one is my gut instinct that cumulatively it's above the complexity limit of what I like to do in a shell script: recursion, hash tables, string processing, regexps. All possible, yes, but easy to make mistakes.
> > 
> > * the string processing and regexp handling would get messier.
> > 
> > * it relies on a dict to represent the dependencies and bash only got hash tables in v4.0, and macOS is never going to move past v3.2 because that's the last version under GPLv2.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I could rewrite it as PHP, although I think it would be a bit longer and a bit uglier.
> > Note also that this is just a tool for developer curiosity/convenience. It's not used in CI, installation, or production, so to a certain extent it doesn't really matter if it breaks and nobody can maintain it.
> 
> This all makes sense, just wanted to make sure we make a conscious choice here and don't just fall back to what is comfortable. In the case we stick with python, I'd vote to have some documentation on Python usage in the repo or at least in the comments of this file that could include
> 
>     1. Versions of python supported
> 
>     2. How to invoke the script
> 
>     3. Which OSes are expected to work (if not all of them)
>        Does it make sense to add any python linting tools to our CI for these scripts, or is that not a priority for these scripts?

Thanks. I did make a conscious choice, but admittedly I didn't articulate it, so you couldn't have know.

I've updated the script docstring to point out that you can run it with `--help` to show the usage -- [argparse](https://docs.python.org/3/library/argparse.html) for the win! --  and added a comment on the supported Python versions.

It definitely works with Python 3.8.x and later (on Ubuntu 20.04 and macOS), and I specifically avoided using the "walrus operator" introduced in 3.8 and there's nothing special in the script so I expect it should work with any Python 3.x on any platform.

We can certainly add Python linting tools, but I had other higher impact linting work I wanted to get done first (see, e.g. #1150), and I didn't want to put additional effort into adding a Python linter until I knew the tool would be accepted.

**Pull request merged**
