### PR TITLE
Remove the incomplete Corrections code

### PR DESCRIPTION
**Pull request by cpeel**
The Corrections code was added in 2004 but has never been used at pgdp.net. Remove this unused and perpetually untested code.

Available in the [remove-corrections-support](https://www.pgdp.org/~cpeel/c.branch/remove-corrections-support/) sandbox.

### CODE REVIEW

**Comment by cpeel** [comment]
Oh good catch, I missed those entirely. I updated the schema too and added an upgrade script to drop the field.

Note that apparently this was used briefly in 2004 as there are 11 projects in PROD that have a `correctedby` entry:
```
mysql> select projectid, correctedby from projects where correctedby!='';
+------------------------+----------------+
| projectid              | correctedby    |
+------------------------+----------------+
| projectID3d21f8f426324 | tonya          |
| projectID3e4efbde4d8e2 | lorax          |
| projectID3ea9ab3b0f29c | sjg1978        |
| projectID3f106a67d00e7 | Jon Ingram     |
| projectID3f1860f15d4f4 | BillFlis       |
| projectID3fa2cda9f1219 | pmerlo         |
| projectID3fac34d099271 | deadlock       |
| projectID3fba49022668d | kit            |
| projectID3fd8d863b8e4d | Malcolm Farmer |
| projectID3ff9b4eb98c50 | turgut         |
| projectID40733d8223419 | wymannmi       |
+------------------------+----------------+
11 rows in set (0.08 sec)
```

**Comment by srjfoo** [comment]
> Oh good catch, I missed those entirely. I updated the schema too and added an upgrade script to drop the field.
> 
> Note that apparently this was used briefly in 2004 as there are 11 projects in PROD that have a `correctedby` entry:
> 
> ```
> mysql> select projectid, correctedby from projects where correctedby!='';
> +------------------------+----------------+
> | projectid              | correctedby    |
> +------------------------+----------------+
> | projectID3d21f8f426324 | tonya          |
> | projectID3e4efbde4d8e2 | lorax          |
> | projectID3ea9ab3b0f29c | sjg1978        |
> | projectID3f106a67d00e7 | Jon Ingram     |
> | projectID3f1860f15d4f4 | BillFlis       |
> | projectID3fa2cda9f1219 | pmerlo         |
> | projectID3fac34d099271 | deadlock       |
> | projectID3fba49022668d | kit            |
> | projectID3fd8d863b8e4d | Malcolm Farmer |
> | projectID3ff9b4eb98c50 | turgut         |
> | projectID40733d8223419 | wymannmi       |
> +------------------------+----------------+
> 11 rows in set (0.08 sec)
> ```

Interesting. That was before DP became a separate entity, so regardless, the code is no longer relevant for our purposes, I believe. DP and PG have changed significantly since then.

Should we document that information in the project comments or project discussions for those projects, or just let it go?

**Comment by lhamilton1** [comment]
I approve

**Review by 70ray — APPROVED** [review]

**Comment by cpeel** [comment]
> > Note that apparently this was used briefly in 2004 as there are 11 projects in PROD that have a `correctedby` entry:
> > ```
> > [snip]
> 
> Should we document that information in the project comments or project discussions for those projects, or just let it go?

I defer to @lhamilton1 but I would just throw that info in the sawiki somewhere for posterity's sake and not bother with updating the project comments.

**Comment by cpeel** [comment]
I've added a page titled `Log of Corrected Projects` in the sawiki that records the list of corrected projects. Updates to that page by SAs is welcome.

**Pull request merged**
