### PR TITLE
Prepare for the R202209 release

### PR DESCRIPTION
**Pull request by cpeel**
Prepare for our usual September release. This won't be merged until just before we're ready to cut the release.

The full list of commits can be seen with:
```bash
git log R202202..master
```

### CODE REVIEW

**Review by chrismiceli — APPROVED** [review]

**Comment by chrismiceli** [comment]
Do we want to start looking at the next LTS Ubuntu? I can help there if you want.

**Review by srjfoo — APPROVED** [review]

**Comment by cpeel** [comment]
> Do we want to start looking at the next LTS Ubuntu? I can help there if you want.

Thank you for the offer! I haven't asked Donovan but I suspect we'll actually wait until late 2024 before we upgrade again (to 2024.04 LTS). While it's gotten a little better recently, it's still quite the pain in the ass to do OS upgrades since the server runs not just Apache/PHP/MySQL but also a mail server (Postfix/Dovecot/Roundcube).

**Review by 70ray — APPROVED** [review]

**Comment by cpeel** [comment]
@srjfoo - I've updated the changelog with the `Math symbols` charsuite. Please let me know if that entry needs updating.

**Comment by srjfoo** [comment]
> @srjfoo - I've updated the changelog with the `Math symbols` charsuite. Please let me know if that entry needs updating.

Looks good to me.

**Review by srjfoo — APPROVED** [review]

**Pull request merged**
