### PR TITLE
convert range parameters to int instead of char

### PR DESCRIPTION
**Pull request by 70ray**
This enables digits to appear in the numerical character picker.

Sandbox at: https://www.pgdp.org/~rp31/c.branch/fix_integers

### CODE REVIEW

**Review by chrismiceli — APPROVED** [review]

**Review by cpeel — COMMENTED** [review]
The `UTF8::range()` function will [also take an int](https://github.com/voku/portable-utf8#rangeintstring-var1-intstring-var2-bool-use_ctype-string-encoding-floatint-step-list) so this seems fine to me. Can you explain more about the problem you are solving so I better understand what to look for in the future?

**Comment by 70ray** [comment]
> The `UTF8::range()` function will [also take an int](https://github.com/voku/portable-utf8#rangeintstring-var1-intstring-var2-bool-use_ctype-string-encoding-floatint-step-list) so this seems fine to me. Can you explain more about the problem you are solving so I better understand what to look for in the future?

The digits 0-9 are missing in the character picker. What appears to be happening is that `U+0030` (etc.) is being converted by `hex_to_chr` to a string `"0"` but PHP  and range are interpreting this as a number `0` rather than a character `"0"`  so giving the range of control characters from 0 to 9. After some experimentaation I found chr_to_int() works. It converts `U+0030` to the number 48 which works correctly.

**Comment by cpeel** [comment]
Ah, got it! Thanks for figuring this out!

**Review by srjfoo — COMMENTED** [review]
I agree -- definitely good catch. (Sorry I wasn't around to do a review earlier.) And I feel embarrassed that I've just been looking at the Basic Latin character picker and making the assumption that we intentionally left the numbers out of that picker.

**Pull request merged**
