### PR TITLE
Prepare for the R202303 release

### PR DESCRIPTION
**Pull request by cpeel**
Update the changelog and upgrade docs for the upcoming R202303 release. This list tries to encapsulate the notable changes without getting into the weeds (that's what `git log` is for). I welcome thoughts if the wording should be updated or if there are additional things we want to include.

A reminder that you can see all of the commits since the last release with `git log R202209..upstream/master`

### CODE REVIEW

**Review by windymilla — APPROVED** [review]
Looks good

**Review by srjfoo — APPROVED** [review]

**Review by chrismiceli — APPROVED** [review]
Do you want help with the VM? It's be fun to learn and try to set it up with the newer Ubuntu LTS.

**Comment by cpeel** [comment]
> Do you want help with the VM? It's be fun to learn and try to set it up with the newer Ubuntu LTS.

I'd love help with the VM! Looks like it hasn't been updated since 2020-09. I don't have a working copy of VMware Fusion anymore so we're welcome to abandon that and just go with VirtualBox if you want.

**Review by 70ray — APPROVED** [review]
Looks good to me.

**Pull request merged**
