### PR TITLE
Ubuntu 16.04 fixes

### PR DESCRIPTION
**Pull request by cpeel**
This fixes a variety of small issues required to work with Ubuntu 16.04. Surprisingly, very very few of these are for PHP 7.x -- the bulk of the work is to support newer versions of MySQL that are less forgiving with lax SQL.

### CODE REVIEW

**Comment by cpeel** [comment]
I did it this way so that we play nice with other database users (MediaWiki and phpBB in our case, could be other users in other cases). Setting stuff in my.conf applies those settings to everything that uses it, which might not want sql_mode changes.

**Comment by wf49670** [comment]
Hadn't thought about other users of the DB server, Casey. Good reason. Might be nice to mention that in the code :)

**Comment by cpeel** [comment]
Good idea. I'll document that and why the margin changes (which were to accommodate the slightly different legend layout changes that came in with jpgraph 4.x).

**Comment by 70ray** [comment]
Can't see any problems.
If the code should work with PHP 7.2, there are same 'each' statements around which are deprecated. Some in tasks.php.

**Comment by cpeel** [comment]
>If the code should work with PHP 7.2, there are same 'each' statements around which are deprecated. Some in tasks.php.

The 7.2 assert fixing came out of investigating the prior commit. There's no hard requirement that this works with 7.2 ... at least not yet. I'll add those to my to-fix list.

**Pull request merged**
