### PR TITLE
Better validate missing $expected_state

### PR DESCRIPTION
**Pull request by cpeel**
This fixes an error seen in the PROD `php_errors` logs a few times. This is due to a user manipulating the `Start Proofreading` link URL and removing the `expected_state` param. While I was here I centralized on using the handy `abort()` tool that outputs some useful links.

If $expected_state is missing the code would fall back to 'new_project' state, which is a valid state but one not within a round and thus cause errors when trying to provide a useful error message. Instead, default to NULL and validate it directly if missing.

Compare:
* Updated message with missing `expected_state` param:
  * [new](https://www.pgdp.org/~cpeel/c/tools/proofers/proof.php?projectid=projectID463e6a9454485) vs [old](https://www.pgdp.org/c/tools/proofers/proof.php?projectid=projectID463e6a9454485)
* Updated message when the provided `expected_state` doesn't match the project's state:
  * [new](https://www.pgdp.org/~cpeel/c/tools/proofers/proof.php?projectid=projectID463e6a9454485&proj_state=P1.proj_avail) vs [old](https://www.pgdp.org/c/tools/proofers/proof.php?projectid=projectID463e6a9454485&proj_state=P1.proj_avail)
* Updated message of trying to proof a project not in the round:
  * [new](https://www.pgdp.org/~cpeel/c/tools/proofers/proof.php?projectid=projectID463e6a9454485&proj_state=P1.proj_unavail) vs [old](https://www.pgdp.org/c/tools/proofers/proof.php?projectid=projectID463e6a9454485&proj_state=P1.proj_unavail)

### CODE REVIEW

**Comment by chrismiceli** [comment]
I wonder why people are manipulating the url in general.

**Review by chrismiceli — APPROVED** [review]

**Review by srjfoo — APPROVED** [review]

**Comment by cpeel** [comment]
> I wonder why people are manipulating the url in general.

I don't know -- it seems weird but when I looked at the logs that IP address was doing otherwise-reasonable things.

**Comment by jj2017** [comment]
I am a culprit. That is what I give newbies in my feedback, the link to the project without the expected state to avoid the warning that the project is no longer in the state that it was when I copied the url. I apologise if this is wrong.

Jacqueline

**Comment by cpeel** [comment]
> I am a culprit. That is what I give newbies in my feedback, the link to the project without the expected state to avoid the warning that the project is no longer in the state that it was when I copied the url. I apologise if this is wrong.

I don't think this is the same thing. The bug wasn't in the link to the project page, it was in the link to the proofreading interface itself. I would hope we aren't telling users how to access the proofreading interface without going through the project page.

Giving links to the project page without the `expected_state` param is completely valid.

**Comment by srjfoo** [comment]
> > I am a culprit. That is what I give newbies in my feedback, the link to the project without the expected state to avoid the warning that the project is no longer in the state that it was when I copied the url. I apologise if this is wrong.
> 
> I don't think this is the same thing. The bug wasn't in the link to the project page, it was in the link to the proofreading interface itself. I would hope we aren't telling users how to access the proofreading interface without going through the project page.
> 
> Giving links to the project page without the `expected_state` param is completely valid.

I was just about to say that I almost always remove `expected_state` from a link to the project page, but that I didn't think that was what this task was about.

**Comment by jj2017** [comment]
Okay, sorry, guilt took over.

jj

**Pull request merged**
