### PR TITLE
Disallow @s in new usernames

### PR DESCRIPTION
**Pull request by cpeel**
By squirrel request: to further discourage people using emails for their usernames, disallow `@`s in new registrations.

Testable in https://www.pgdp.org/~cpeel/c.branch/disallow-ats-in-new-usernames/

### CODE REVIEW

**Review by srjfoo — APPROVED** [review]

**Comment by lhamilton1** [comment]
I approve

**Review by windymilla — APPROVED** [review]
Works fine for me. 

I did wonder if it would be good for the error message to also say "Don't use your email address" to aid those who can't see why their username is being rejected. However, I don't think it's worth it - a user needs to be able to understand "Valid characters are..." not having the at-sign. So, not worth the extra code complication.

**Review by 70ray — APPROVED** [review]

**Review by chrismiceli — APPROVED** [review]
Might be worth adding some phpunit tests to this.

**Comment by cpeel** [comment]
Unit tests added!

**Pull request merged**
