### PR TITLE
Prompt the user to upload .zip files

### PR DESCRIPTION
**Pull request by cpeel**
For zip file uploads, tell the browser that we accept .zip files
to prevent the user from selecting a file that isn't a .zip file
(assumimg the browser supports it).

### CODE REVIEW

**Comment by mlazaric** [comment]
This behaves strangely on vivaldi: 

image

(notice the "Zip archive, **unknown**" and how it doesn't hide the non zip files)

image

Manually selecting "Zip archive" from the dropdown does hide non zip files:

image

These are all from https://www.pgdp.org/~cpeel/c/tools/project_manager/remote_file_manager.php

Not sure why it added the unknown part.

**Comment by mlazaric** [comment]
Chrome seems to have the same strange behavior.

**Comment by cpeel** [comment]
The update in `remote_file_manager.php` is for the non-javascript version of the uploader, which you probably aren't using unless you've disabled JS.

**Comment by srjfoo** [comment]
I'm not seeing that behavior in either FF or Safari, but that may just mean that I don't have any of that kind of file sitting around. Afaik, I have javascript enabled.

**Pull request merged**
