### PR TITLE
Rename SF genre to SF&F

### PR DESCRIPTION
**Pull request by srjfoo**
GM request: Rename the `Science Fiction` genre to `Science Fiction & Fantasy`. This acknowledges explicitly how the genre is actually used.

Branch sandbox at [rename-sf-genre](https://www.pgdp.org/~srjfoo/c.branch/rename-sf-genre/).

### CODE REVIEW

**Comment by cpeel** [comment]
As this is our first genre with `&` we need to make sure that it is escaped correctly everywhere in the HTML. Some places that I've found:
```diff
diff --git a/pinc/ProjectSearchResults.inc b/pinc/ProjectSearchResults.inc
index 507f690da..259a0b515 100644
--- a/pinc/ProjectSearchResults.inc
+++ b/pinc/ProjectSearchResults.inc
@@ -218,7 +218,7 @@ class GenreColumn extends Column
         if ($prefix != "") {
             $genre = $prefix." ".$genre;
         }
-        echo $genre;
+        echo html_safe($genre);
     }
 }

diff --git a/project.php b/project.php
index befa14d13..a90ba8e22 100644
--- a/project.php
+++ b/project.php
@@ -424,7 +424,7 @@ function do_project_info_table()
     echo_row_a(_("Title"), $project->nameofwork, true);
     echo_row_a(_("Author"), $project->authorsname, true);
     echo_row_a(_("Language"), $project->language);
-    echo_row_a(_("Genre"), _($project->genre));
+    echo_row_a(_("Genre"), _($project->genre), true);

     echo_row_a(_("Difficulty"), _($project->difficulty));

```

**Comment by srjfoo** [comment]
> As this is our first genre with `&` we need to make sure that it is escaped correctly everywhere in the HTML. Some places that I've found:
> 
> ```diff
> diff --git a/pinc/ProjectSearchResults.inc b/pinc/ProjectSearchResults.inc
> index 507f690da..259a0b515 100644
> --- a/pinc/ProjectSearchResults.inc
> +++ b/pinc/ProjectSearchResults.inc
> @@ -218,7 +218,7 @@ class GenreColumn extends Column
>          if ($prefix != "") {
>              $genre = $prefix." ".$genre;
>          }
> -        echo $genre;
> +        echo html_safe($genre);
>      }
>  }
> 
> diff --git a/project.php b/project.php
> index befa14d13..a90ba8e22 100644
> --- a/project.php
> +++ b/project.php
> @@ -424,7 +424,7 @@ function do_project_info_table()
>      echo_row_a(_("Title"), $project->nameofwork, true);
>      echo_row_a(_("Author"), $project->authorsname, true);
>      echo_row_a(_("Language"), $project->language);
> -    echo_row_a(_("Genre"), _($project->genre));
> +    echo_row_a(_("Genre"), _($project->genre), true);
> 
>      echo_row_a(_("Difficulty"), _($project->difficulty));
> ```

Thanks -- I think the next question is whether we should avoid that altogether and have me replace the ampersand with 'and'. I used the ampersand primarily because of string length.

**Comment by cpeel** [comment]
> Thanks -- I think the next question is whether we should avoid that altogether and have me replace the ampersand with 'and'. I used the ampersand primarily because of string length.

Well we should be doing that escaping anyway, but I don't feel strongly if you want to punt and use `and` instead.

**Comment by srjfoo** [comment]
> > Thanks -- I think the next question is whether we should avoid that altogether and have me replace the ampersand with 'and'. I used the ampersand primarily because of string length.
> 
> Well we should be doing that escaping anyway, but I don't feel strongly if you want to punt and use `and` instead.

👍  -- no, I have no objection to making the change, especially if we should be doing the escaping, anyway.

**Comment by chrismiceli** [comment]
> 
> 
> > > Thanks -- I think the next question is whether we should avoid that altogether and have me replace the ampersand with 'and'. I used the ampersand primarily because of string length.
> > 
> > 
> > Well we should be doing that escaping anyway, but I don't feel strongly if you want to punt and use `and` instead.
> 
> 👍 -- no, I have no objection to making the change, especially if we should be doing the escaping, anyway.

I don't mind taking a look at the escaping separate of this ticket for genre and other elated fields perhaps.

**Comment by srjfoo** [comment]
> > > > Thanks -- I think the next question is whether we should avoid that altogether and have me replace the ampersand with 'and'. I used the ampersand primarily because of string length.
> > > 
> > > 
> > > Well we should be doing that escaping anyway, but I don't feel strongly if you want to punt and use `and` instead.
> > 
> > 
> > 👍 -- no, I have no objection to making the change, especially if we should be doing the escaping, anyway.
> 
> I don't mind taking a look at the escaping separate of this ticket for genre and other elated fields perhaps.

That might be a good idea, anyway. I haven't updated the MR yet, but I found some of them -- however, I don't know enough to know what I'm missing. I'll get a revised MR up in a bit, and we can look at it then.

**Comment by srjfoo** [comment]
> > > > > Thanks -- I think the next question is whether we should avoid that altogether and have me replace the ampersand with 'and'. I used the ampersand primarily because of string length.
> > > > 
> > > > 
> > > > Well we should be doing that escaping anyway, but I don't feel strongly if you want to punt and use `and` instead.
> > > 
> > > 
> > > 👍 -- no, I have no objection to making the change, especially if we should be doing the escaping, anyway.
> > 
> > 
> > I don't mind taking a look at the escaping separate of this ticket for genre and other elated fields perhaps.
> 
> That might be a good idea, anyway. I haven't updated the MR yet, but I found some of them -- however, I don't know enough to know what I'm missing. I'll get a revised MR up in a bit, and we can look at it then.

I don't know if I got everything, or if what I did get was correct. I did update the sandbox, and what I checked seems to work there, but just the display looking okay doesn't mean the code is necessarily correct.

**Review by chrismiceli — APPROVED** [review]
I'll gladly resolve any conflicts after this merges with my MR.

**Comment by cpeel** [comment]
Thanks @chrismiceli - I'll get this merged in and if you can rebase your MR we can get it in too.

**Pull request merged**
