### PR TITLE
release_queue.php: Remove dead code

### PR DESCRIPTION
**Pull request by bpfoley**
Hapax legomenon, baby!

### CODE REVIEW

**Review by cpeel — APPROVED** [review]
Confirmed this function is not used in this repo or `noncvs`.

Bye dead code! 👋

**Comment by srjfoo** [comment]
<grin> -- I got distracted learning new vocabulary! (but I totally agree!)

**Comment by jmdyck** [comment]
(I was curious if that function was ever used. It seems not. @cpeel introduced it a few months ago in PR #950.)

**Comment by cpeel** [comment]
Whoops, well, glad Brian helped clean up after my mess 😆

**Pull request merged**
