### PR TITLE
Updated English proofreading summaries

### PR DESCRIPTION
**Pull request by srjfoo**
Per request from the GM, updated the English versions of the
proofreading summary PDF and ODT files. The PDF is available for review here: [PDF summary](https://www.pgdp.org/~srjfoo/c.branch/update-proof-summary-en/faq/proofing_summary.pdf).

For comparison, here's the version being superseded: [old PDF summary](https://www.pgdp.net/c/faq/proofing_summary.pdf).

### CODE REVIEW

**Comment by cpeel** [comment]
Should the date at the top of the page be changed? Odd to have both new and old dated 25 May 2020.

**Comment by srjfoo** [comment]
> Should the date at the top of the page be changed? Odd to have both new and old dated 25 May 2020.

Good catch -- fixed.

With all the people who'd already proofread it, including me, none of us caught that!

**Comment by chrismiceli** [comment]
> 
> 
> > Should the date at the top of the page be changed? Odd to have both new and old dated 25 May 2020.
> 
> Good catch -- fixed.
> 
> With all the people who'd already proofread it, including me, none of us caught that!

Did it make it through P3?! ;)

**Comment by srjfoo** [comment]
> > > Should the date at the top of the page be changed? Odd to have both new and old dated 25 May 2020.
> > 
> > 
> > Good catch -- fixed.
> > With all the people who'd already proofread it, including me, none of us caught that!
> 
> Did it make it through P3?! ;)

More than that! It made it all the way through F2 and PP, and was caught in PPV!

**Pull request merged**
