### PR TITLE
Italic foot

### PR DESCRIPTION
**Pull request by 70ray**
This enables footnote markers to be italic or other tagged letters. Also improve some variable names and add tests.

Addresses https://www.pgdp.net/c/tasks.php?task_id=2013

Sandbox at: https://www.pgdp.org/~rp31/c.branch/italic_foot

### CODE REVIEW

**Review by srjfoo — COMMENTED** [review]
@70ray -- could you double-check [this page](https://www.pgdp.org/~rp31/c.branch/italic_foot/tools/project_manager/downloadproofed.php?project=projectID5690905894029&image=104.png&round_num=4)? I was testing both footnotes with markup and multiple footnote marker styles. When I ran Preview on that page, the first footnote at the bottom of the page got a "possible issue: Footnote should be a letter or a number" warning for me.

**Comment by 70ray** [comment]
> @70ray -- could you double-check [this page](https://www.pgdp.org/~rp31/c.branch/italic_foot/tools/project_manager/downloadproofed.php?project=projectID5690905894029&image=104.png&round_num=4)? I was testing both footnotes with markup and multiple footnote marker styles. When I ran Preview on that page, the first footnote at the bottom of the page got a "possible issue: Footnote should be a letter or a number" warning for me.

I hadn't allowed for italic numbers. I'll adjust it.

**Comment by chrismiceli** [comment]
> > @70ray -- could you double-check [this page](https://www.pgdp.org/~rp31/c.branch/italic_foot/tools/project_manager/downloadproofed.php?project=projectID5690905894029&image=104.png&round_num=4)? I was testing both footnotes with markup and multiple footnote marker styles. When I ran Preview on that page, the first footnote at the bottom of the page got a "possible issue: Footnote should be a letter or a number" warning for me.
> 
> I hadn't allowed for styled numbers. I'll adjust it.

The changes and variable names look good to me. After you add support for styled numbers, maybe add a test case too?

**Comment by 70ray** [comment]
> > > @70ray -- could you double-check [this page](https://www.pgdp.org/~rp31/c.branch/italic_foot/tools/project_manager/downloadproofed.php?project=projectID5690905894029&image=104.png&round_num=4)? I was testing both footnotes with markup and multiple footnote marker styles. When I ran Preview on that page, the first footnote at the bottom of the page got a "possible issue: Footnote should be a letter or a number" warning for me.
> > 
> > 
> > I hadn't allowed for styled numbers. I'll adjust it.
> 
> The changes and variable names look good to me. After you add support for styled numbers, maybe add a test case too?

Added styled numbers and test case.

**Review by srjfoo — APPROVED** [review]

**Review by chrismiceli — APPROVED** [review]

**Pull request merged**
