### PR TITLE
Remove code for opening the project page in an existing window

### PR DESCRIPTION
**Pull request by 70ray**

### CODE REVIEW

**Comment by cpeel** [comment]
Your change does more than remove the code for opening the project in an existing, named window. It also removes the code that opens a new proofing window of a specific size. Personally, I think that's a better solution in today's tab + window world, but this is a big enough change that it probably needs a wider community discussion.

I'd love to rip out `pinc/resolution.inc` and the user prefs that use it, so I'm 100% behind this change.

**Comment by 70ray** [comment]
Perhaps we could just make it work like it does now except for re-using an old window which shouldn't be too controversial.

**Comment by cpeel** [comment]
> Perhaps we could just make it work like it does now except for re-using an old window which shouldn't be too controversial.

Agreed. I think if you just rip out the `$window_name_base` nonsense and just pass `_blank` to `window.open` that might work.

**Comment by 70ray** [comment]
New revised pull request made

**Pull request closed without merging**
