### PR TITLE
Update to volunteer certification disclaimer

### PR DESCRIPTION
**Pull request by srjfoo**
The [Certification of Volunteer](https://www.pgdp.net/wiki/DP_Official_Documentation:General/Certification_of_Volunteer_Work) Work disclaimer wording in the wiki has recently been updated. This PR realigns the wording on the home page with the updated disclaimer. GM request.

### CODE REVIEW

**Review by bpfoley — APPROVED** [review]

**Review by cpeel — APPROVED** [review]
NTS: Squash this in with a comment about squashing this into `e9720de3ba` at some point.

**Review by chrismiceli — APPROVED** [review]

**Comment by srjfoo** [comment]
On reading again through the original version that I opened the PR with, I found that it had some rough spots, so I worked with Linda and Walt to hopefully get a final version.

If anyone has any wording tweak suggestions, please feel free to make suggestions. (I added a commit instead of squashing so that anyone interested could see the progression).

**Review by wf49670 — APPROVED** [review]

**Comment by lhamilton1** [comment]
I approve.

**Review by cpeel — APPROVED** [review]
LGTM!

**Pull request merged**
