### PR TITLE
Add search forms to the Members and Team listings

### PR DESCRIPTION
**Pull request by cpeel**
This adds a search form the to Members and Team listings. In a separate commit I styled the search forms on the Stats Central page. I'm not enamored with that one so I'm happy if folks think we should just drop that commit. [Task 1926](https://www.pgdp.net/c/tasks.php?action=show&task_id=1926)

See the [member-team-search](https://www.pgdp.org/~cpeel/c.branch/member-team-search/) sandbox.

### CODE REVIEW

**Comment by srjfoo** [comment]
> ... In a separate commit I styled the search forms on the Stats Central page. I'm not enamored with that one so I'm happy if folks think we should just drop that commit.

I agree. I think the real problem, though, is that there are two tables, side-by-side, that take up more horizontal space than the table below them (which is narrower, if not restricted by the browser window width, than the tables below it). The current version doesn't draw the eye because it doesn't have the color and the extra width from the table layout.

Very cool for the team and member list pages to have a search form on them. Looks good!

**Review by srjfoo — APPROVED** [review]

**Comment by cpeel** [comment]
> > ... In a separate commit I styled the search forms on the Stats Central page. I'm not enamored with that one so I'm happy if folks think we should just drop that commit.
> 
> I agree. I think the real problem, though, is that there are two tables, side-by-side, that take up more horizontal space than the table below them (which is narrower, if not restricted by the browser window width, than the tables below it). The current version doesn't draw the eye because it doesn't have the color and the extra width from the table layout.

Sorry, is that a "you agree we should drop the changes to the stats central"?

**Comment by srjfoo** [comment]
> > > ... In a separate commit I styled the search forms on the Stats Central page. I'm not enamored with that one so I'm happy if folks think we should just drop that commit.
> > 
> > 
> > I agree. I think the real problem, though, is that there are two tables, side-by-side, that take up more horizontal space than the table below them (which is narrower, if not restricted by the browser window width, than the tables below it). The current version doesn't draw the eye because it doesn't have the color and the extra width from the table layout.
> 
> Sorry, is that a "you agree we should drop the changes to the stats central"?

Yes, I agree we should drop the changes to the stats central page. My apologies for the blather -- I was just trying to analyze why it didn't quite fit.

**Comment by cpeel** [comment]
I've updated the commit to do better parameter validation and try to align the files closer together style-wise. This needs to be retested to make sure I didn't horribly break anything.

**Review by srjfoo — APPROVED** [review]
>This needs to be retested to make sure I didn't horribly break anything.

I don't see any brokenness -- everything seems to work as it should!

**Review by chrismiceli — APPROVED** [review]

**Review by 70ray — APPROVED** [review]

**Pull request merged**
