### PR TITLE
Split simplify

### PR DESCRIPTION
**Pull request by 70ray**
This is the version of image widget we want to present for evaluation.
The text both has a splitter and is editable only for a user with Mentor, PF or Squirrel access.
The drag bar markers are not implemented. 

Sandbox at https://www.pgdp.org/~rp31/c.branch/split_simplify

### CODE REVIEW

**Review by chrismiceli — APPROVED** [review]

**Review by srjfoo — APPROVED** [review]
Looks good to me.

The `User.inc` bug fix has been merged and rolled out to TEST -- should that be removed from this MR?

**Comment by chrismiceli** [comment]
> 
> 
> Looks good to me.
> 
> The `User.inc` bug fix has been merged and rolled out to TEST -- should that be removed from this MR?

It is still needed in image-widget branch which this merged into.

**Comment by srjfoo** [comment]
> > Looks good to me.
> > The `User.inc` bug fix has been merged and rolled out to TEST -- should that be removed from this MR?
> 
> It is still needed in image-widget branch which this merged into.

Oh, right ... 🤦‍♀️

**Comment by cpeel** [comment]
For merging purposes it would be better if I cherry-picked the now-merged commit into this branch separately. Let me do that and Ray can remove that change from this MR.

**Pull request merged**
