### PR TITLE
Cache page stats graphs as long as possible

### PR DESCRIPTION
**Pull request by cpeel**
Generating the page stats is very resource intensive and can take a very long time. Cache the stats for as long as is reasonable which in some cases is up to a month. This mitigates https://github.com/DistributedProofreaders/dproofreaders/issues/1025

Clarify that memcached accepts both a timestamp *and* seconds from now: https://github.com/memcached/memcached/wiki/Programming#expiration

Testable in https://www.pgdp.org/~cpeel/c.branch/cache-graphs-longer/ -- note that the HTML for the page as a comment that shows exactly what the expiration times are evaluated to.

### CODE REVIEW

**Comment by srjfoo** [comment]
A couple of questions:

In the comment text, I'm seeing
```html
    <!--          Now: 2024-01-27T02:24:26+00:00
    Tomorrow midnight: 2024-01-28T00:00:00+00:00
     First next month: 2024-02-01T02:24:26+00:00
      First next week: 2024-01-28T00:00:00+00:00
```
"First next month" time of day is not based on midnight, but on "Now". Is that what you wanted?

Second question -- would it be useful to have the expiration time on the graphs themselves, or would that just be confusing to viewers?

**Review by chrismiceli — APPROVED** [review]

**Comment by windymilla** [comment]
Just checking - I wasn't quite sure from reading the memcached docs and the code...
Is a number of seconds that is greater than 30 days interpreted as a unix timestamp instead? Where we do "first day of next month" are we using the "number of seconds"? 
If both of those are true, does the following cause an issue?
If it is Jan 1st, then the first day of next month would be Feb 1st, i.e. 31 days later, which is more than 30 days, so a number of seconds from "now" on Jan 1st would get interpreted as a timestamp.

**Comment by cpeel** [comment]
> Where we do "first day of next month" are we using the "number of seconds"?

We are not. We're using some human-readable strings to create a DateTimeImmutable object and then from that outputting a timestamp to pass as the expiration.

Interestingly I was originally calculating the number of seconds before looking at the memcached docs to see how big a number it would accept and learning we could pass in timestamps instead.

**Review by windymilla — APPROVED** [review]
Thanks for confirmation

**Comment by cpeel** [comment]
> "First next month" time of day is not based on midnight, but on "Now". Is that what you wanted?

It was not and I've fixed it - thanks for catching that.

> Second question -- would it be useful to have the expiration time on the graphs themselves, or would that just be confusing to viewers?

I think having the expiration time on the graphs is going to be confusing (and make the code more confusing because the graph could would need to know when they expire, which is handled by a layer higher up). We could update the graphs to contain when they were generated and that would probably make more sense to users but I'm not sure if the effort is worth the return?

**Review by 70ray — APPROVED** [review]

**Comment by srjfoo** [comment]
> > Second question -- would it be useful to have the expiration time on the graphs themselves, or would that just be confusing to viewers?
> 
> I think having the expiration time on the graphs is going to be confusing (and make the code more confusing because the graph could would need to know when they expire, which is handled by a layer higher up). We could update the graphs to contain when they were generated and that would probably make more sense to users but I'm not sure if the effort is worth the return?

No, I don't think it's worth going to a lot of effort. And even that would likely be confusing. Since different graphs have different refresh times, it would probably be much more likely to be confusing than helpful. Thanks!

**Review by srjfoo — APPROVED** [review]

**Pull request merged**
